Update db structure
ilia-anikeev/graph-researcher pull request #5
Opened 2024-05-13 20:26 UTC by ilia-anikeev

2024-05-18 07:25 UTC, honeyfill requested changes

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/controller/GraphResearchController.java
>              throw new RuntimeException(e);
throw выкинет exception никуда, потому что это конец эндпоинта сервера, не нужно так делать

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/controller/GraphResearchController.java
>              throw new RuntimeException(e);
same

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/controller/SaveController.java
>              throw new RuntimeException(e);
same

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +    private final Connection connection;
Немного устарело, лучше использовать новый интерфейс: https://docs.oracle.com/javase/8/docs/api/javax/sql/DataSource.html

DataSource хранить, нужно в каждом методе делать `try (Connection conn = ds.getConnection()) {}`, так лучше работать с открытием ресурсов

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +            String NAME = "db.username";
Капсом обычно пишут `static` константы, лучше просто `name`

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +            throw new RuntimeException(e);
Exception в конструкторе выглядит тоскливо, как раз из-за того, что не стоит хранить connection

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +                "VALUES(" + userID + ", " + graph.getMetadata().isDirected + ", "
`VALUES(?, ?, ?, ?,?)`, потом внутри try-with-resources сделать statement.setString(i++, paramValue)

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +        String sql = "INSERT INTO graph_metadata(user_id, is_directed, is_weighted, has_self_loops, has_multiple_edges) " +
В oracle нет boolean типа

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +    private void saveVertices(int graphID, List<Vertex> vertices) {
Зачем эта обертка?

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +    private void saveEdges(int graphID, List<Edge> edges) {
Зачем эта обертка?

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +    private void saveBridges(int graphID, List<Edge> edges) {
Для всех трех вопрос: зачем

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +    private void saveMaxClique(int graphID, List<Vertex> clique) {
думаю вопрос понятен

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +        String sql1 = "DELETE FROM graph_research_info WHERE graph_id = " + graphID;
Посмотри `MERGE INTO`

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +        String sql = "SELECT * FROM graph_research_info WHERE graph_id = " + graphID;
setParam

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +    private List<List<Vertex>> getConnectedComponents(int graphID) {
зачем

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +    private List<List<Vertex>> getBlocks(int graphID) {
зачем

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +        String sql = "SELECT component_number, index, data FROM " + tableName + " WHERE graph_id = " + graphID;
setParam для where

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +                    componentsMap.get(rs.getInt("component_number")).add(new Vertex(rs.getInt("index"), rs.getString("data")));
Вынеси создание Vertex, так год дублируется, да и понятнее меньше становится

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +    private List<Vertex> getVertices(int graphID) {
зачем

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +    private List<Edge> getEdges(int graphID) {
просто буду ставить у каждой обертки ? )

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +    private List<List<Vertex>> getColoring(int graphID) {
?

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +    public void createUser(int userID) {
User не должен иметь ничего общего с работой с графом 
Лучше унести в отдельный репозиторий

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +    private void deleteVertices(int graphID) {
?

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +    private void deleteEdges(int graphID) {
?

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +        String sql = "DELETE FROM " + tableName + " WHERE graph_id = " + graphID;
setParam

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +        String sql = "DELETE FROM " + tableName + " WHERE graph_id = " + graphID;
setParam

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +    private void deleteBridges(int graphID) {
?

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +    private void deleteColoring(int graphID) {
?

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +        String sql = "DELETE FROM kuratowski_subgraph WHERE graph_id = " + graphID;
setParam

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +    public void initDB() {
одноразовая функция, не репозиторий не должен быть частью DDL процессов 
лучше вынести это в какой-нибудь sql файл, который будет запускаться при создании бд

в целом в учебном проекте можно оставить, но в целом так никто не делает

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +        String sql = "CREATE TABLE minimal_vertex_separator(id SERIAL PRIMARY KEY, graph_id INT, component_number INT, index INT, data TEXT)";
чем graph_id не PK?

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +        String sql = "CREATE TABLE minimal_vertex_separator(id SERIAL PRIMARY KEY, graph_id INT, component_number INT, index INT, data TEXT)";
в целом вопрос к каждому созданию таблиц

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +    public void deleteDB() {
не надо так делать)
даже в учебном проекте лучше не создавать таких методов

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/util/ParseResearchInfo.java
>      public ParseResearchInfo(GraphResearchInfo info, int graphID) {
Класс это сущность, не очень хорошо когда класс является действием

2024-05-18 07:25 UTC, honeyfill commented on server/src/main/java/com/graphResearcher/util/ParsingUtil.java
> +        final int EMPTY_MASK = 0;
мне больше нравились статик переменные

2024-05-18 07:25 UTC, honeyfill commented on server/src/test/java/com/graphResearcher/GraphResearcherApplicationTests.java
> +        TestUtil.equals(graph1, receivedGraph);
TestUtil?

2024-05-18 07:25 UTC, honeyfill commented on server/src/test/java/com/graphResearcher/TestUtil.java
> +    public static void equals(List<?> lhs, List<?> rhs) {
существуте assertEquals двух листок

2024-05-18 07:25 UTC, honeyfill commented on server/src/test/java/com/graphResearcher/TestUtil.java
> +    public static void equals(GraphResearchInfo lhs, GraphResearchInfo rhs) {
по факту это equals у класса GraphResearchInfo, давайте это унесем туда и удалим этот класс

2024-05-18 07:25 UTC, honeyfill commented on ui/src/App.js
> +  function createVertex() {
а как сюда проросли изменения Кати?

2024-05-24 17:38 UTC, ilia-anikeev commented on ui/src/App.js
> +  function createVertex() {
![im](https://github.com/ilia-anikeev/graph-researcher/assets/112325838/bed7c9e4-1f54-438f-a87b-26861943dbc0)

2024-05-24 17:41 UTC, ilia-anikeev commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +        String sql = "INSERT INTO graph_metadata(user_id, is_directed, is_weighted, has_self_loops, has_multiple_edges) " +
пу-пу-пу, всмысле нету? Как-то ведь оно отрабатывает

2024-05-24 17:45 UTC, ilia-anikeev commented on server/src/main/java/com/graphResearcher/repository/DataBaseManager.java
> +        String sql = "CREATE TABLE minimal_vertex_separator(id SERIAL PRIMARY KEY, graph_id INT, component_number INT, index INT, data TEXT)";
Потому что как правило в каждой таблице лежат по несколько строк с одинаковым graph_id, то есть нет уникальности

2024-05-24 19:06 UTC, merged